apiVersion: v1
kind: Service
metadata:
  name: resurrexi-io
  namespace: resurrexi-io
  labels:
    app: resurrexi-io
spec:
  type: NodePort
  selector:
    app: resurrexi-io
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30801
    protocol: TCP
    name: http
